### PR TITLE
Add GlusterFS

### PR DESCRIPTION
**Pull request by bswinnerton**

### CODE REVIEW

**Comment by edasque** [comment]
So are you moving away from docker compose and will move to Helm?

Tell me more about GlusterFS and why you had to move to it.

**Comment by bswinnerton** [comment]
> So are you moving away from docker compose

Yep! At least moving towards Kubernetes for most things. That's actually been the intention of this repository from [the start](https://brooks.sh/2017/12/22/configuring-kvm-on-clear-linux/). But I imagine moving over more stateful applications like Prometheus and Postgres will take a little longer.

> and will move to Helm?

I'm not too sure about Helm. While I've heard of it, I'm not well versed in when its the right tool for the job.

> Tell me more about GlusterFS and why you had to move to it.

It's more of an addition than something I had to move to. Kubernetes has the concept of [persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) which I'd need for things like [Grafana's volumes](https://github.com/bswinnerton/home-lab/blob/5512327b7ff0d796975bb57ed78d901daa902eb1/docker/grafana/docker-compose.yml#L9-L11). GlusterFS (running _on_ Kubernetes _for_ Kubernetes) will provide a shared network storage to enable this.

**Comment by edasque** [comment]
Did you find a shortcut to moving from docker compose to Kunernetes? How many nodes? What is your master node going to be?

**Comment by bswinnerton** [comment]
There's a tool to help convert docker-compose config to Kubernetes called [`kompose`](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/#kompose-convert).

There are [two physical hosts](https://github.com/bswinnerton/home-lab/tree/b078b859e2bf7b26cae778d1601babc5df331fc7#the-home-lab), each running three virtual machines. One virtual machine on each host is the master(s), and the other four machines are worker nodes.

**Pull request merged**
